# Generated by Django 5.0.4 on 2024-04-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_matchhighlight_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhighlight',
            name='testing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
