# Generated by Django 5.0.4 on 2024-04-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_player_player_name_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='schedule',
        ),
    ]
