# Generated by Django 5.0.4 on 2024-04-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_highlightlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhighlight',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
