# Generated by Django 5.0.4 on 2024-04-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_matchhighlight_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhighlight',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
