# Generated by Django 5.0.4 on 2024-04-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_matchhighlight_liked_by_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HighlightLike',
        ),
    ]
