# Generated by Django 5.0.4 on 2024-04-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_highlightlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_players',
            field=models.ManyToManyField(related_name='team1_players', to='user.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_players',
            field=models.ManyToManyField(related_name='team2_players', to='user.player'),
        ),
    ]
