# Generated by Django 5.0.4 on 2024-04-30 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_match_team1_players_match_team2_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchhighlight',
            name='highlight_url',
        ),
        migrations.AddField(
            model_name='match',
            name='uploaded_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
